#define MEDGENET_VERSION_MAJOR 1
#define MEDGENET_VERSION_MINOR 1
#define MEDGENET_VERSION_PATCH 0
#define MEDGENET_VERSION_BUILD 0

#define MEDGENET_VERSION_VALUE MEDGENET_VERSION_MAJOR,MEDGENET_VERSION_MINOR,MEDGENET_VERSION_PATCH,MEDGENET_VERSION_BUILD
#define MEDGENET_VERSION_STRING "1.1.0"
